describe('Outlet Creation', () => {
  beforeEach(() => {
    cy.visit('http://d95site2.localhost/user/login')
    cy.get('.user-login-form')
      .find('div').first()
      .find('input')
      .type('gymadmin1').should('have.value', 'gymadmin1')
    cy.get('.user-login-form')
      .find('div').first().next()
      .find('input')
      .type('gymadmin1').should('have.value', 'gymadmin1')
    cy.get('.user-login-form')
      .submit()
    cy.get('.page-title')
      .should('contain', 'gymadmin1')
  })

  it('Verify ClimbSG Username Label', () => {
    cy.get('nav')
      .contains('Content')
      .click()
    cy.get('.button-action')
      .should('have.attr', 'href', '/node/add')
      .and('contain','Add content')
      .click()
    cy.get('.block__content')
      .find('dt')
      .should('have.attr', 'href', '/node/add/outlet')
      .and('contain','Outlet')
      .click()
  })
})
