describe('Check Site Login', () => {
  beforeEach(() => {
    cy.visit('http://d95site2.localhost/')
    // cy.get('.dropdown-menu').contains('Navigation').click()
  })

  it('Verify ClimbSG Username Label', () => {
    cy.get('.menu').contains('Log in').click()
    cy.get('.user-login-form')
      .find('div')
      .find('div')
      .contains('Enter your ClimbSG username.')
  })

  it('Attempt Fake Login', () => {
      cy.get('.menu').contains('Log in').click()
      cy.get('.user-login-form')
        .find('div').first()
        .find('input')
        .type('myfake@email.com')
      cy.get('.user-login-form')
        .find('div').first().next()
        .find('input')
        .type('mypassword').should('have.value', 'mypassword')
      cy.get('.user-login-form')
        .submit()
      cy.get('.messages--error')
        .children()
        .should('contain', 'Unrecognized username or password.')
  })
  it('Gym Admin Login', () => {
      cy.get('.menu').contains('Log in').click()
      cy.get('.user-login-form')
        .find('div').first()
        .find('input')
        .type('gymadmin1').should('have.value', 'gymadmin1')
      cy.get('.user-login-form')
        .find('div').first().next()
        .find('input')
        .type('gymadmin1').should('have.value', 'gymadmin1')
      cy.get('.user-login-form')
        .submit()
      cy.get('.page-title')
        .should('contain', 'gymadmin1')
  })
})
