<?php
use Drupal\Core\Form\FormStateInterface;

// node-climbing-type-form
function waffles_mod_form_node_climbing_type_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['tos'] = [
    '#type' => 'fieldset',
    '#title' => t('Terms of service'),
    '#weight' => -100,
  ];

  $form['tos']['tos_text'] = [
    '#markup' => t('Terms of service ... blah blah blah ...'),
    '#prefix' => '<p>',
    '#suffix' => '</p>',
  ];

  $form['tos']['tos_agree'] = [
    '#type' => 'checkbox',
    '#title' => t('I agree to the terms of service'),
  ];

  // Add a validation handler where we'll check the checkbox above.
  $form['#validate'][] = 'alterform_form_validate';
}

function alterform_form_validate(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $tos_agree = $form_state->getValue('tos_agree');
  if ($tos_agree !== 1) {
    $form_state->setErrorByName('tos_agree', t('You must agree to the terms of service to continue.'));
  }
}


// node_article_form
function waffles_mod_form_node_article_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['tos'] = [
    '#type' => 'fieldset',
    '#title' => t('Terms of service'),
    '#weight' => -100,
  ];

  // Add a validation handler where we'll check the checkbox above.
  // $form['#validate'][] = 'alterform_form_validate';
}

/**
 * Implements hook_form_alter().
 */
function waffles_mod_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  /* Your code here */
  ksm($form_id);
}
